-- Tạo cơ sở dữ liệu
CREATE DATABASE QuanLyThuVien;
GO
-- Sử dụng cơ sở dữ liệu vừa tạo
USE QuanLyThuVien;
GO
CREATE TABLE VITRI (
    MAVT CHAR(10) PRIMARY KEY,       
    TENVITRI NVARCHAR(50) NOT NULL  
);
CREATE TABLE THELOAI (
    MATL CHAR(10) PRIMARY KEY,       
    TENTL NVARCHAR(50) NOT NULL,    
    MAVT CHAR(10) NOT NULL,         
    CONSTRAINT fk_THELOAI_VITRI FOREIGN KEY (MAVT) REFERENCES VITRI(MAVT)
);
CREATE TABLE TACGIA (
    MATG CHAR(10) PRIMARY KEY,       -- Mã tác giả
    TENTG NVARCHAR(50) NOT NULL     -- Tên tác giả
);
CREATE TABLE SACH (
    MASACH CHAR(10) PRIMARY KEY,     -- Mã sách
    TENSACH NVARCHAR(50) NOT NULL,  -- Tên sách
    MATG CHAR(10) NOT NULL,         -- Mã tác giả
    MATL CHAR(10) NOT NULL,         -- Mã thể loại
    CONSTRAINT fk_SACH_TACGIA FOREIGN KEY (MATG) REFERENCES TACGIA(MATG),
    CONSTRAINT fk_SACH_THELOAI FOREIGN KEY (MATL) REFERENCES THELOAI(MATL)
);
CREATE TABLE SINHVIEN (
    TENSV NVARCHAR(50) NOT NULL,    -- Tên sinh viên
    LOP NVARCHAR(50) NOT NULL       -- Lớp
);
CREATE TABLE THEMUON (
    MATM CHAR(10) PRIMARY KEY,       -- Mã thẻ mượn
    NGAYLAPTHE DATE NOT NULL,        -- Ngày lập thẻ
    NGAYHETHAN DATE NOT NULL,        -- Ngày hết hạn
    MASV CHAR(10) NOT NULL,          -- Mã sinh viên
    CONSTRAINT fk_THEMUON_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
);
 CREATE TABLE NHANVIEN (
    MANV CHAR(10) PRIMARY KEY,       -- Mã nhân viên
    TENNV NVARCHAR(50) NOT NULL,    -- Tên nhân viên
    CHUCVU NVARCHAR(50) NOT NULL    -- Chức vụ
);

CREATE TABLE PHIEUMUONTRA (
    MAPMT CHAR(10) PRIMARY KEY,      -- Mã phiếu mượn trả
    NGAYMUON DATE NOT NULL,          -- Ngày mượn
    NGAYTRA DATE,                    -- Ngày trả
    MANV CHAR(10) NOT NULL,          -- Mã nhân viên
    CONSTRAINT fk_PHIEUMUONTRA_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
CREATE TABLE CAPNHATPHIEUMUONTRA (
    MAPMT CHAR(10) NOT NULL,         -- Mã phiếu mượn trả
    MASACH CHAR(10) NOT NULL,        -- Mã sách
    MATM CHAR(10) NOT NULL,          -- Mã thẻ mượn
    SOLUONG INT NOT NULL,            -- Số lượng sách mượn
    THOIGIAN DATE NOT NULL,          -- Thời gian cập nhật
    CONSTRAINT PK_CAPNHATPHIEUMUONTRA PRIMARY KEY (MAPMT, MASACH, MATM),
    CONSTRAINT fk_CAPNHATPMT_PHIEUMUONTRA FOREIGN KEY (MAPMT) REFERENCES PHIEUMUONTRA(MAPMT),
    CONSTRAINT fk_CAPNHATPMT_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    CONSTRAINT fk_CAPNHATPMT_THEMUON FOREIGN KEY (MATM) REFERENCES THEMUON(MATM)
);
